version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: saas_postgres_db
    environment:
      POSTGRES_DB: saas_db
      POSTGRES_USER: asadulshaown
      POSTGRES_PASSWORD: asadulshaown1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: saas_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=saas_db
      - DB_USER=asadulshaown
      - DB_PASSWORD=asadulshaown1234
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: saas_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: